apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anon-blog-config
  namespace: anon-blog
spec:
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/anon-blog/prod/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/anon-blog/prod/postgres
        property: password
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/anon-blog/prod/api
        property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: anon-blog
spec:
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/anon-blog/prod/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/anon-blog/prod/postgres
        property: password
