apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: anon-blog
  namespace: anon-blog-prod
spec:
  routes:
  - match: Host(`abapi.vengarl.com`)
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anon-blog-cert
spec:
  dnsNames:
    - abapi.vengarl.com
