resources:
- ../../base
namespace: anon-blog-prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: external-secrets-patch.yaml
- path: ingress-route-patch.yaml
- path: deployment-patch.yaml
