import os

SECRET_KEY = os.getenv('SECRET_KEY')
SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
CORS_DOMAIN = os.getenv('CORS_DOMAIN', '*')
RECAPTCHA_SECRET = os.getenv('RECAPTCHA_SECRET')
