apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: anon-blog
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/anon-blog/postgres
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/anon-blog/postgres
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anon-blog-config
  namespace: anon-blog
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: anon-blog-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        creds.json: |
          {
            "SQLALCHEMY_DATABASE_URI": "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres.anon-blog.svc.cluster.local:5432/anonblog",
            "SECRET_KEY": "{{ .SECRET_KEY }}"
          }
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/anon-blog/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/anon-blog/postgres
        property: password
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/anon-blog/api
        property: secret_key
