"""empty message

Revision ID: 672cf2d77ab7
Revises: e3322ede36bf
Create Date: 2022-12-30 10:19:54.414818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672cf2d77ab7'
down_revision = 'e3322ede36bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
